### ISSUE TITLE
Empty object when throwing object with error property

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/js-docker-isolation-provider#7]
# Code
```ts
async () => {
  try {
    throw new Error('Hello world!');
  } catch (error) {
    console.error({ error });
    throw {
      errors: [error],
    };
  }
};
```

# What I see in docker logs
Note that this error is taken from another handler but behavior is the same
```
{
  error: ReferenceError: Cannot access 'logDepth' before initialization
      at eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:51:74)
      at Generator.next (<anonymous>)
      at /node_modules/apollo-link-ws/node_modules/tslib/tslib.js:115:75
      at new Promise (<anonymous>)
      at __awaiter (/node_modules/apollo-link-ws/node_modules/tslib/tslib.js:111:16)
      at getConfig (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:49:20)
      at eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:18:30)
      at Generator.next (<anonymous>)
      at /node_modules/apollo-link-ws/node_modules/tslib/tslib.js:115:75
      at new Promise (<anonymous>)
}
rejected { errors: [ {} ] }
```

# Expected
rejected { errors: [ Error ] }  (something like this)

# Acutal
rejected { errors: [ {} ] }

**Comment by FreePhoenix888** [comment]
# Workaround
```ts
throw {
  error: util.inspect(error)
}
```

Note that this is not solution. Error will become string. The problem is in js-docker-isolation-provider which does not handle deep objects
